# Generated by Django 6.0.7 on 2026-07-10 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('barrio', models.CharField(choices=[('Centro', 'Centro'), ('El Limón', 'El Limón'), ('Jaime Roldós', 'Jaime Roldós'), ('El Pangui', 'El Pangui'), ('Tungurahua', 'Tungurahua'), ('Ciudadela Municipal', 'Ciudadela Municipal'), ('El Ejido', 'El Ejido'), ('La Vega', 'La Vega'), ('Las Palmeras', 'Las Palmeras'), ('San Francisco', 'San Francisco'), ('Bombuscaro', 'Bombuscaro'), ('Cumbaratza', 'Cumbaratza'), ('Otro', 'Otro')], default='Centro', max_length=50, verbose_name='Barrio/Sector')),
                ('direccion', models.CharField(blank=True, help_text='Calle, número, referencia...', max_length=200, verbose_name='Dirección completa')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroGato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gato', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='ID del gato')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('tipo_raza', models.CharField(choices=[('mestizo', 'Mestizo'), ('definida', 'Raza definida')], default='mestizo', max_length=20, verbose_name='Tipo de raza')),
                ('raza_definida', models.CharField(blank=True, choices=[('persa', 'Persa'), ('siames', 'Siamés'), ('maine_coon', 'Maine Coon'), ('bengali', 'Bengalí'), ('ragdoll', 'Ragdoll'), ('británico_pelo_corto', 'Británico de Pelo Corto'), ('abisinio', 'Abisinio'), ('sphynx', 'Sphynx'), ('scottish_fold', 'Scottish Fold'), ('angora', 'Angora Turco'), ('burmés', 'Burmés'), ('bosque_noruego', 'Bosque de Noruega'), ('himalayo', 'Himalayo'), ('otra', 'Otra')], max_length=50, null=True, verbose_name='Raza específica')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('edad_meses', models.PositiveIntegerField(verbose_name='Edad (meses)')),
                ('estado_salud', models.CharField(choices=[('sano', 'Sano'), ('enfermo', 'Enfermo')], default='sano', max_length=10, verbose_name='Estado de salud')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (lpm)')),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (rpm)')),
                ('tiene_carnet_vacunacion', models.BooleanField(default=False, verbose_name='¿Tiene carnet de vacunación?')),
                ('vacunas', models.JSONField(blank=True, default=list, help_text='Lista de vacunas que tiene el felino', verbose_name='Vacunas aplicadas')),
                ('antecedente_transfusion', models.BooleanField(default=False, verbose_name='Antecedente transfusional')),
                ('resultado_kit_ic', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('ND', 'No determinable')], max_length=2, verbose_name='Resultado kit inmunocromatografía')),
                ('fecha_muestreo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de muestreo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatos', to='core.propietario', verbose_name='Propietario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de gato',
                'verbose_name_plural': 'Registros de gatos',
                'ordering': ['-fecha_muestreo', '-creado_en'],
            },
        ),
    ]
