# Generated by Django 6.0.7 on 2026-07-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_direccion_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='barrio',
            field=models.CharField(choices=[('Centro', 'Centro'), ('El Limón', 'El Limón'), ('Jaime Roldós', 'Jaime Roldós'), ('Tungurahua', 'Tungurahua'), ('Ciudadela Municipal', 'Ciudadela Municipal'), ('El Ejido', 'El Ejido'), ('La Vega', 'La Vega'), ('Las Palmeras', 'Las Palmeras'), ('San Francisco', 'San Francisco'), ('Isidro Ayora', 'Isidro Ayora'), ('Cumbaratza', 'Cumbaratza'), ('Guadalupe', 'Guadalupe'), ('Imbana', 'Imbana'), ('Sabanilla', 'Sabanilla'), ('San Carlos de las Minas', 'San Carlos de las Minas'), ('Timbara', 'Timbara'), ('Otro', 'Otro')], default='Centro', max_length=50, verbose_name='Barrio/Sector'),
        ),
    ]
