# Generated by Django 6.0.6 on 2026-09-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_propietario_barrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrogato',
            name='hematocrito',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de glóbulos rojos obtenido por microhematocrito centrifugado', max_digits=5, null=True, verbose_name='Hematocrito (%)'),
        ),
    ]
